Ft user reset password
atlp-rwanda/ecommerce-app-predators-fe pull request #13
Opened 2023-06-05 21:56 UTC by faid-terence

#### What does this PR do?
This pull request adds a new feature to the application: a reset password page. The reset password page allows users to reset their passwords in case they forget or want to change them.
#### Description of Task to be completed?
In case the users password is forgotten, functionality should exists to reset the password via an associated and email account.

#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout branch-?
npm i
npm run dev
http://localhost:5173/reset-password-page
```

#### What are the relevant pivotal tracker/Trello stories?
Trello [Link](https://trello.com/c/SXhRxTFm/55-users-should-be-presented-with-a-reset-password-link) (#-55)

#### Screenshots (if appropriate)
![My Task](https://github.com/atlp-rwanda/ecommerce-app-predators-fe/assets/122970729/426afa00-ae88-4f77-a388-9d8e2f249b34)

2023-06-06 09:01 UTC, faid-terence commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be presented with a reset password link](https://trello.com/c/SXhRxTFm/55-users-should-be-presented-with-a-reset-password-link)

2023-06-06 09:01 UTC, faid-terence commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be presented with a reset password link](https://trello.com/c/SXhRxTFm/55-users-should-be-presented-with-a-reset-password-link)

2023-06-12 06:45 UTC, Muhet approved these changes
GOOD JOB

2023-06-12 07:05 UTC, yobuir approved these changes

2023-06-13 09:09 UTC, chanceDira requested changes
Nice work @faid-terence  just few issues

2023-06-13 09:09 UTC, chanceDira commented on src/pages/PasswordConfirminationPage..tsx
> +    dispatch(updatePassword(resetData) as any)
Let's not use any keyword, create an interface for resetData

2023-06-13 09:09 UTC, chanceDira commented on src/pages/RegisterPage.tsx
> +    const registrationStatus = useSelector((state: any) => state.user.status);
no "any" keyword

2023-06-13 15:22 UTC, closed without merging