#42 Two factor authentication
atlp-rwanda/ecommerce-app-predators-fe pull request #15
Opened 2023-06-07 08:55 UTC by Muhet

#### What does this PR do?
Seller login with higher security

#### Description of Task to be completed?

Users that require a higher level of security (Sellers) should be able to turn on 2FA where authentication to the application also incudes a an extra factor i.e SMS or Authentications codes.
After a successful login, Sellers should be redirected to their dashboard

#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout branch-?
npm i
npm run dev
```

#### What are the relevant pivotal tracker/Trello stories?
Trello [Link]() (#-?)

#### Screenshots (if appropriate)
![loginPredator](https://github.com/atlp-rwanda/ecommerce-app-predators-fe/assets/86248137/d77ff6ff-c66c-4201-9487-6004a3a9a058)
![twofactor](https://github.com/atlp-rwanda/ecommerce-app-predators-fe/assets/86248137/565ab93f-d97d-48c9-b836-4c3909237c2e)

2023-06-11 22:11 UTC, faid-terence approved these changes

2023-06-12 06:54 UTC, yobuir requested changes

2023-06-12 06:54 UTC, yobuir commented on README.md
> +=======
You can remove this ` <<<<<<< HEAD `

2023-06-12 07:20 UTC, Vanessa-bitega approved these changes

2023-06-12 07:22 UTC, Muhet commented on README.md
> +=======
I removed it

2023-06-12 07:31 UTC, yobuir approved these changes

2023-06-12 07:31 UTC, yobuir commented on src/redux/action/otpAction.tsx
> +const API_URL = 'http://localhost:3000/auth/';
are we using local url or hosted one?

2023-06-12 07:44 UTC, ALVINdimpos approved these changes

2023-06-12 07:44 UTC, ALVINdimpos commented on src/redux/action/otpAction.tsx
> +const API_URL = 'http://localhost:3000/auth/';
can can u use hosted link

2023-06-12 07:46 UTC, ALVINdimpos requested changes

2023-06-12 07:46 UTC, ALVINdimpos commented on src/redux/action/otpAction.tsx
> +const API_URL = 'http://localhost:3000/auth/';
try by using using hosted link

2023-06-12 08:27 UTC, Muhet commented on src/redux/action/otpAction.tsx
> +const API_URL = 'http://localhost:3000/auth/';
No I replaced it with the hosted one. check it

2023-06-12 08:27 UTC, Muhet commented on src/redux/action/otpAction.tsx
> +const API_URL = 'http://localhost:3000/auth/';
I did check it again

2023-06-12 12:15 UTC, ALVINdimpos approved these changes

2023-06-13 09:21 UTC, chanceDira approved these changes
Good job

2023-06-13 09:21 UTC, merged