Ft password expiration prompts 40
atlp-rwanda/ecommerce-app-predators-fe pull request #18
Opened 2023-06-07 20:29 UTC by NTElissa

#### What does this PR do?
This PR introduces a new feature that prompts users to change their passwords every x amount of time

#### Description of Task to be completed?
GIVEN that the user logs ,and the password has expired
THEN the user should be redirected to Password update page

#### How should this be manually tested?
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout branch-?
npm i
npm run dev
#### What are the relevant pivotal tracker/Trello stories?
Trello Link: https://trello.com/c/EJYJUc13

#### Screenshots (if appropriate)

2023-06-14 11:38 UTC, Muhet requested changes
can you fix the conflict that you have

2023-06-15 09:42 UTC, Vanessa-bitega approved these changes

2023-06-15 10:14 UTC, ALVINdimpos approved these changes

2023-06-15 10:27 UTC, Muhet approved these changes
great job

2023-06-15 11:23 UTC, ALVINdimpos approved these changes

2023-06-15 13:29 UTC, kagaba-etienne approved these changes

2023-06-15 14:42 UTC, chanceDira approved these changes
Nice work @NTElissa

2023-06-15 14:42 UTC, merged