#34 Feature:  A seller should be able to delete item from their collection
atlp-rwanda/ecommerce-app-predators-fe pull request #20
Opened 2023-06-11 20:48 UTC by yobuir

#### What does this PR do?
A seller should be able to delete a specific item from their collection when it's no longer needed

#### Description of Task to be completed?
Seller should be able to delete a specific item from collection when it's
no longer on offer 
- When the seller clicks on delete item a confirm dialogue box should popup to confirm item deletion

#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout branch-?
npm i
npm run dev
```

#### What are the relevant pivotal tracker/Trello stories?
Trello ([link](https://trello.com/c/I1ntJ3hD/34-a-seller-should-be-able-to-delete-a-specific-item-from-their-collection))

#### Screenshots (if appropriate)
![Screenshot (78)](https://github.com/atlp-rwanda/ecommerce-app-predators-fe/assets/62539654/4fafdb2c-f3f0-46af-a651-e40e8aac2833)

2023-06-14 11:40 UTC, Muhet requested changes
Can you fix those conflict and also you test are not passing

2023-06-15 16:24 UTC, faid-terence approved these changes

2023-06-15 16:24 UTC, ALVINdimpos approved these changes

2023-06-16 07:10 UTC, Vanessa-bitega approved these changes

2023-06-16 09:29 UTC, chanceDira requested changes
Nice work @yobuir 
Below are some suggested changes

2023-06-16 09:29 UTC, chanceDira commented on src/components/notification/Notification.tsx
> +function Notification(props: any) {
Create an interface here, Let's not use "any"

2023-06-16 09:29 UTC, chanceDira commented on src/components/sample.tsx
>  export const add = (a: any, b: any) => {
Create interface

2023-06-16 09:29 UTC, chanceDira commented on src/components/sidebar/Sidebar.tsx
> +export default function Sidebar(props: any) {
create interface

2023-06-16 09:29 UTC, chanceDira commented on src/redux/action/ProductAction.tsx
> +  async ({data}: any, thunkAPI) => {
remove "any"

2023-06-16 10:34 UTC, chanceDira approved these changes
Looking good

2023-06-16 10:39 UTC, Muhet approved these changes
great progress

2023-06-16 10:40 UTC, merged