ft/admin-disable-acount-29: disable account
atlp-rwanda/ecommerce-app-predators-fe pull request #26
Opened 2023-06-14 23:42 UTC by ALVINdimpos

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout branch-?
npm i
npm run dev
```

#### What are the relevant pivotal tracker/Trello stories?
Trello [Link]() (#-?)

#### Screenshots (if appropriate)

2023-06-16 09:48 UTC, faid-terence approved these changes
Good Job @ALVINdimpos

2023-06-16 13:02 UTC, kagaba-etienne approved these changes
Good Job!

2023-06-16 13:03 UTC, NTElissa approved these changes
good progress

2023-06-16 14:08 UTC, chanceDira approved these changes, later dismissed
Nice work @ALVINdimpos 
Just few issues

2023-06-16 14:08 UTC, chanceDira commented on src/components/table/UserTable.tsx
> +    dispatch(getAllUsers() as any);
can you use interface here,

2023-06-16 14:10 UTC, chanceDira requested changes
Create interfaces, Let's not use any

2023-06-16 15:36 UTC, nili-alu approved these changes
great job

2023-06-18 15:21 UTC, Vanessa-bitega approved these changes

2023-06-19 12:08 UTC, chanceDira approved these changes
Nice work

2023-06-19 12:08 UTC, merged