#33 Feature: User Update Profile
atlp-rwanda/ecommerce-app-predators-fe pull request #28
Opened 2023-06-15 13:23 UTC by kagaba-etienne

#### What does this PR do?

- Creates a UI to enable user in profile updating
- Adds necessary intergration with backend to facilitate user in editing his/her profile

#### Description of Task to be completed?

> Users should be able to amend/edit their profiles depending on a change of preference to the entire disclosure of the individual user
>
> As a User
> I want to get my profile created once I register for the application.
I want my profile to display my Personal Information name, email,gender, birthdate, preferred language, preferred currency ,where you live, Billing Address (check the right fields of the billing address)
>
> Acceptance Criteria
> I want to be able to Edit my profile, but I should NOTbe able to edit another users profile
> Scenario:
> Given User registers to be a member of the App.
> Registration is done.
> User Profile is created.
> A timestamp is associated to the profile

#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout ft-user-update-profile
npm i
npm run dev
```

#### What are the relevant pivotal tracker/Trello stories?
[Card #33](https://trello.com/c/TmVCsXQw)

2023-06-19 15:45 UTC, Muhet approved these changes
Great job

2023-06-19 15:46 UTC, yobuir approved these changes

2023-06-19 16:07 UTC, Vanessa-bitega approved these changes

2023-06-19 17:18 UTC, nili-alu approved these changes
good job

2023-06-20 10:31 UTC, chanceDira requested changes
Nice job @kagaba-etienne just one thing

2023-06-20 10:31 UTC, chanceDira commented on src/redux/action/profileAction.tsx
> +    async (profile: any, thunkAPI) => {
can you use interface here

2023-06-20 10:32 UTC, kagaba-etienne commented on src/redux/action/profileAction.tsx
> +    async (profile: any, thunkAPI) => {
okay sure!

2023-06-20 10:39 UTC, faid-terence approved these changes

2023-06-20 10:57 UTC, chanceDira approved these changes
Good

2023-06-20 10:57 UTC, merged