feature:Buyer manages own wishlist
atlp-rwanda/ecommerce-app-predators-fe pull request #39
Opened 2023-06-26 19:37 UTC by faid-terence

#### What does this PR do?
Adds Buyer Wishlist Management Functionalities

#### Description of Task to be completed?

> Acceptance criteria:

GIVEN that the buyer is on a product page

WHEN the buyer clicks the ""Add to Wishlist"" button or a button to add the item to the wishlist without leaving the current page (optional)
THEN the item should be added to the buyer's wishlist and the buyer should see a confirmation message

#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout branch-ft-buyer-manages-wishlist-53
npm i
npm run dev
```

#### What are the relevant pivotal tracker/Trello stories?
Trello [Link](https://trello.com/c/gBoJ48jP/53-a-buyer-should-be-able-to-manage-their-wishlist
![wishlist](https://github.com/atlp-rwanda/ecommerce-app-predators-fe/assets/122970729/d3689d5e-4515-4593-89c4-74fee68ec85a)
) (#-53)

#### Screenshots (if appropriate)

2023-07-05 09:35 UTC, yobuir approved these changes

2023-07-05 09:44 UTC, nili-alu approved these changes

2023-07-05 09:58 UTC, chanceDira requested changes
Below are some requested changes, Also try to fix CI, they are failing.

2023-07-05 09:58 UTC, chanceDira commented on src/components/sample.tsx
> +export const add = (a: number, b: number) => {
I think we are not using this file, we can remove it.

2023-07-05 09:58 UTC, chanceDira commented on src/components/table/UserTable.tsx
>    getAllUsers: any;
use interface instead of any

2023-07-05 09:58 UTC, chanceDira commented on src/components/wishlist/WishlistTable.tsx
> +  Product: any;
I guess this should be a string instead of any

2023-07-05 09:58 UTC, chanceDira commented on src/redux/action/productActions.tsx
> +<<<<<<< HEAD
fix this rebase issue

2023-07-05 09:58 UTC, chanceDira commented on src/redux/store/Store.tsx
> +<<<<<<< HEAD
rebasing issue

2023-07-05 14:59 UTC, faid-terence commented on src/components/table/UserTable.tsx
>    getAllUsers: any;
> use interface instead of any

I think this is Alvin's work ! not mine

2023-07-06 14:44 UTC, Vanessa-bitega approved these changes

2023-07-10 07:47 UTC, chanceDira requested changes
Take a look on the below issue

2023-07-10 07:47 UTC, chanceDira commented on .github/workflows/slack.yml
> +<<<<<<< HEAD
rebase issue

2023-07-11 05:10 UTC, chanceDira approved these changes
Looking good

2023-07-11 05:10 UTC, merged