#19 feature: Track order status
atlp-rwanda/ecommerce-app-predators-fe pull request #43
Opened 2023-06-29 15:23 UTC by yobuir

#### What does this PR do?
A buyer should be able to track their order status
#### Description of Task to be completed?
A buyer should be able to know the status of his/her order after sign in 
#### How should this be manually tested?
```
git clone https://github.com/atlp-rwanda/ecommerce-app-predators-fe.git
cd ecommerce-app-predators-fe
git checkout track-order-status-19
npm i
npm run dev
```
#### What are the relevant pivotal tracker/Trello stories?
Trello [Link](https://trello.com/c/ewShIM4D/19-a-buyer-should-be-able-to-track-their-order-status)

#### Screenshots (if appropriate)

2023-07-04 13:26 UTC, ALVINdimpos approved these changes

2023-07-05 09:40 UTC, nili-alu approved these changes

2023-07-05 10:43 UTC, chanceDira requested changes
Good work, just some requested changes below

2023-07-05 10:43 UTC, chanceDira commented on bash.exe.stackdump
> +Stack trace:
Can you clarify the use of this file?

2023-07-05 10:43 UTC, chanceDira commented on src/pages/buyer/Orders.tsx
> +  data: any | null | undefined;
data inside the OrdersData interface can have first interface then other options like null and undefined

2023-07-05 12:17 UTC, Vanessa-bitega approved these changes

2023-07-12 14:04 UTC, chanceDira approved these changes
Looking good

2023-07-12 14:04 UTC, merged