setting up redux
atlp-rwanda/ecommerce-app-predators-fe pull request #5
Opened 2023-05-29 14:28 UTC by Vanessa-bitega

What does this PR do?
This pull request implements the setup of Redux in our client application.

Description of Task to be completed
1. Installed Redux and Redux Toolkit to manage the application state.
2. Created Redux store with the necessary configuration.
3. Defined actions and reducers to handle the application state.
4. Connected Redux store to the application components using the `useSelector` and `useDispatch` hooks.
5. Updated the relevant components to use Redux for state management.

How should this be manually tested?
1. Run the application and perform actions that trigger state changes.
2. Verify that the application behaves correctly and the state is updated as expected.
3. Test different scenarios to ensure the Redux store is working correctly.

Screenshots (if appropriate)
N/A

2023-05-31 07:50 UTC, Muhet requested changes
Can you fix the conflict?

2023-05-31 07:56 UTC, faid-terence approved these changes

2023-05-31 08:46 UTC, Vanessa-bitega commented
> Can you fix the conflict?

Done

2023-05-31 09:52 UTC, ALVINdimpos approved these changes

2023-05-31 12:05 UTC, NTElissa approved these changes
good progress

2023-06-01 07:10 UTC, chanceDira requested changes
Nice work @Vanessa-bitega , just one thing

2023-06-01 07:10 UTC, chanceDira commented on src/components/ProductListing.tsx
> +    (state: { products: { data: any } }) => state.products.data
Let's not use any keyword, build an interface for product then use it

2023-06-02 09:43 UTC, chanceDira approved these changes

2023-06-02 09:58 UTC, Muhet approved these changes
good job Abewe

2023-06-02 10:01 UTC, merged